<div class="helloworld">
   <h3>Hello World</h3> 
   <p class="text-firstname"></p>
   <p class="text-lastname"></p>
   <p class="full-name"></p> 
</div>
<script>
    require(['jquery','myvalidation'],function($, myValidation){
        console.log("Require js loaded");
        $(document).ready(function(){
            $(".text-firstname").html(myValidation.firstname);
            $(".text-lastname").html(myValidation.lastname);
            $(".full-name").html(myValidation.showDetail());

        });
        console.log(myValidation);

    })
</script>